---
# yaml-language-server: $schema=https://schema.blue-build.org/recipe-v1.json
# image will be published to ghcr.io/<user>/<name>
name: hyprland
# description will be included in the image's metadata
description: This is my personal OS image.

# the base image to build on top of (FROM) and the version tag to use
base-image: quay.io/fedora-ostree-desktops/base-atomic
image-version: 42 # module configuration, executed in order

# you can include multiple instances of the same module
modules:
  - type: containerfile
    snippets:
      - COPY --from=ghcr.io/ublue-os/akmods:main-42 /rpms /tmp/rpms
      - COPY --from=ghcr.io/ublue-os/akmods:main-42 /kernel-rpms /tmp/rpms/kernel
      - RUN find /tmp/rpms
      - RUN rpm -q ublue-os-akmods-addons || rpm-ostree install /tmp/rpms/ublue-os/ublue-os-akmods-addons*.rpm
  - type: script
    scripts:
      - installSignedKernel.sh

  - type: containerfile
    snippets:
      - RUN rpm-ostree install just powerstat
      - COPY --from=ghcr.io/ublue-os/config:latest /rpms/ublue-os-udev-rules.noarch.rpm /
      - COPY --from=ghcr.io/ublue-os/config:latest /rpms/ublue-os-update-services.noarch.rpm /
      - COPY --from=ghcr.io/ublue-os/config:latest /rpms/ublue-os-signing.noarch.rpm /
      - COPY --from=ghcr.io/ublue-os/config:latest /rpms/ublue-os-luks.noarch.rpm /
      - COPY --from=ghcr.io/ublue-os/config:latest /rpms/ublue-os-just.noarch.rpm /
      - RUN rpm -ivh /ublue-os-udev-rules.noarch.rpm
      - RUN rpm -ivh /ublue-os-update-services.noarch.rpm
      - RUN rpm -ivh /ublue-os-signing.noarch.rpm
      - RUN rpm -ivh /ublue-os-luks.noarch.rpm
      - RUN rpm -ivh /ublue-os-just.noarch.rpm

  - type: script
    scripts:
      - installAndroidUdev.sh
      - ensureAutoUpdates.sh
      - fixUpstreamICDLoaderBug.sh

  - from-file: ../modules/greetd-module.yaml
  - from-file: ../modules/display-module.yaml
  - from-file: ../modules/file-manager-module.yaml
  - from-file: ../modules/dev-module.yaml
  - from-file: ../modules/media-module.yaml
  - from-file: ../modules/system-module.yaml
  - from-file: ../modules/security-module.yaml
  - from-file: ../modules/network-module.yaml

  - type: files
    files:
      - source: system
        destination: / # copies files/system/* (* means everything inside it) into your image's root folder /

  - type: script
    scripts:
      - removeUnusedRepos.sh
      - regenerateInitramfs.sh

  - type: signing # this sets up the proper policy & signing files for signed images to work fully

